version: "3"
services:
  backend:
    build: ./backend
    environment:
      - STAGE=dev
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
      - MONGO_DB=dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    restart: unless-stopped
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo/data:/data/db
    ports:
      - "27017:27017"
    command: --auth
    restart: unless-stopped
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
